
on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            -
                name: Versatile PyInstaller
                uses: sayyid5416/pyinstaller@v1.8.0
                with:
                    spec: 'build.spec'
                    requirements: 'requirements.txt'
                    upload_exe_with_name: "BookReader"
    
    release:
        runs-on: ubuntu-latest
        needs: build
        
        steps:
            -
                name: Download artifact
                uses: actions/download-artifact@v5
                with:
                    name: BookReader
                    path: release-files
            
            -
                name: Create release
                uses: ncipollo/release-action@v1
                with:
                    artifacts: "release-files/**"
                    allowUpdates: true
